name: Build and Deploy Code

on:
  push:
#    branches:
#      - main
#    types: [closed]

jobs:
#  if: ${{ github.event.pull_request.merged }}
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hi
        run: echo "Hello, Eugene!"
